-keep class com.river.flows.eastward.waves.bmain.SwccsTool { *; }

-keep class com.river.flows.eastward.waves.csywc.ysr.YwccsMRecent { *; }
-keep class com.river.flows.eastward.waves.contens.BikerLC { *; }
-keep class com.river.flows.eastward.waves.bmain.FAnScwc { *; }
-keep class com.appsflyer.** { *; }
-keep class kotlin.jvm.internal.** { *; }
-keep public class com.tradplus.** { *; }
-keep class com.tradplus.ads.** { *; }
-keepattributes !SourceFile
-dontshrink
